version: '3.8'

services:
  # 1. Database Service (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Expose port for external tools (DBeaver, IntelliJ, etc.)
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Persist data if container stops
    healthcheck: # Controllo salute per dire a Spring quando il DB è pronto
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend Service (Spring Boot)
  backend:
    build: ./backend # context is the 'backend' folder
    container_name: finance_backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      db: # Wait for DB to start
        condition: service_healthy
    environment:
      # These variables override application.properties
      SPRING_DATASOURCE_URL: ${DATABASE_ROOT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # Validate schema matches entities (safer than 'update')
      SPRING_JPA_HIBERNATE_DDL_AUTO: update