services:
  # 1. Database Service (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Expose port for external tools (DBeaver, IntelliJ, etc.)
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Persist data if container stops
    healthcheck: # Controllo salute per dire a Spring quando il DB è pronto
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend Service (Spring Boot)
  backend:
    build:
      context: ./backend
      target: development
    container_name: finance_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    depends_on:
      db: # Wait for DB to start
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # These variables override application.properties
      SPRING_DATASOURCE_URL: ${DATABASE_ROOT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      # Validate schema matches entities (safer than 'update')
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_LONG_EXPIRATION: ${JWT_LONG_EXPIRATION}
      JWT_SHORT_EXPIRATION: ${JWT_SHORT_EXPIRATION}

      ADMIN_EMAIL: ${ADMIN_EMAIL}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

      DEMO_ENABLED: ${DEMO_ENABLED}

      BACKUP_CONTAINER_NAME: ${BACKUP_CONTAINER_NAME}
      BACKUP_DB_NAME: ${BACKUP_DB_NAME}
      BACKUP_DIR: ${BACKUP_DIR}
      BACKUP_ENCRYPTION_PASS: ${BACKUP_ENCRYPTION_PASS}

      R2_ACCESS_KEY: ${R2_ACCESS_KEY}
      R2_SECRET_KEY: ${R2_SECRET_KEY}
      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_BUCKET: ${R2_BUCKET}
      R2_ENABLED: ${R2_ENABLED}

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: finance_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env
#    depends_on:
#      - backend
    environment:
      VITE_API_URL: ${BACKEND_URL}
      VITE_ALLOWED_HOSTS: ${FRONTEND_URL}